samples:
  todo:
    event-store:
      in-memory: false

kopring:
  bricks:
    audit-log:
      jdbc:
        dialect: postgresql
        flyway:
          enabled: true
    event-sourcing:
      jdbc:
        dialect: postgresql
        flyway:
          enabled: true
    outbox:
      jdbc:
        dialect: postgresql
        flyway:
          enabled: true
