#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_PATH="$ROOT_DIR/docs/generated/project-facts.md"
CHECK=false

usage() {
  cat <<'EOF'
Usage: scripts/docs-facts.sh [--check] [--output <path>]

Generates factual project documentation extracted from Gradle, Spring metadata,
and Kotlin source annotations. The output is intended as source material for AI
README updates, not as polished user documentation.

Options:
  --check         fail when the generated facts differ from the target file
  --output PATH   write to PATH instead of docs/generated/project-facts.md
  --help          show this help
EOF
}

for arg in "$@"; do
  case "$arg" in
    --check)
      CHECK=true
      ;;
    --output)
      shift
      OUTPUT_PATH="${1:-}"
      [[ -n "$OUTPUT_PATH" ]] || {
        echo "--output requires a path" >&2
        exit 2
      }
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $arg" >&2
      usage >&2
      exit 2
      ;;
  esac
done

module_dir() {
  printf '%s' "$1" | tr ':' '/'
}

module_name() {
  local module="$1"
  printf '%s' "${module##*:}"
}

module_kind() {
  local name
  name="$(module_name "$1")"

  case "$name" in
    *-autoconfigure)
      printf 'autoconfigure'
      ;;
    *-starter)
      printf 'starter'
      ;;
    *-test-support)
      printf 'test-support'
      ;;
    *)
      printf 'sample'
      ;;
  esac
}

dependency_lines() {
  local build_file="$1"

  if [[ ! -f "$build_file" ]]; then
    return 0
  fi

  awk '
    /^dependencies[[:space:]]*\{/ { in_deps = 1; depth = 1; next }
    in_deps {
      depth += gsub(/\{/, "{")
      depth -= gsub(/\}/, "}")
      if (depth <= 0) { in_deps = 0; next }
      line = $0
      sub(/^[[:space:]]+/, "", line)
      sub(/[[:space:]]+$/, "", line)
      if (line ~ /^(api|implementation|compileOnly|testImplementation|testRuntimeOnly)\(/) {
        print line
      }
    }
  ' "$build_file"
}

configuration_properties() {
  local module_path="$1"

  find "$module_path/src/main/kotlin" -type f -name '*.kt' 2>/dev/null |
    sort |
    while IFS= read -r file; do
      awk -v file="$file" '
        /@ConfigurationProperties\("/ {
          prefix = $0
          sub(/^.*@ConfigurationProperties\("/, "", prefix)
          sub(/".*$/, "", prefix)
          next
        }
        prefix != "" && /^(data[[:space:]]+)?class[[:space:]]+[A-Za-z0-9_]+/ {
          class_name = $0
          sub(/^.*class[[:space:]]+/, "", class_name)
          sub(/[(:<[:space:]].*$/, "", class_name)
          sub(/^\.\//, "", file)
          print "- `" prefix "` -> `" class_name "` (" file ")"
          prefix = ""
        }
      ' "$file"
    done
}

spring_factories_processors() {
  local factories_file="$1"

  if [[ ! -f "$factories_file" ]]; then
    return 0
  fi

  awk '
    /^[[:space:]]*#/ { next }
    /^org\.springframework\.boot\.EnvironmentPostProcessor=/ { capture = 1; next }
    capture {
      line = $0
      gsub(/\\/, "", line)
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
      if (line != "") {
        print "- `" line "`"
      }
      capture = 0
    }
  ' "$factories_file"
}

auto_configurations() {
  local imports_file="$1"

  if [[ ! -f "$imports_file" ]]; then
    return 0
  fi

  sed '/^[[:space:]]*$/d; /^[[:space:]]*#/d' "$imports_file" |
    while IFS= read -r line; do
      printf -- '- `%s`\n' "$line"
    done
}

generate() {
  cd "$ROOT_DIR"

  modules=()
  while IFS= read -r module; do
    modules+=("$module")
  done < <(sed -n 's/^include("\(.*\)")/\1/p' settings.gradle.kts)

  cat <<'EOF'
# Project Facts

This file is generated by `scripts/docs-facts.sh`.
Use it as factual source material when updating human-authored documentation.

EOF

  echo "## Modules"
  echo
  for module in "${modules[@]}"; do
    printf -- '- `%s` (%s)\n' "$module" "$(module_kind "$module")"
  done
  echo

  echo "## Starter Pairs"
  echo
  for module in "${modules[@]}"; do
    [[ "$(module_kind "$module")" == "starter" ]] || continue
    local name="${module%-starter}"
    local autoconfigure="${name}-autoconfigure"
    if printf '%s\n' "${modules[@]}" | grep -Fqx "$autoconfigure"; then
      printf -- '- `%s` -> `%s`\n' "$module" "$autoconfigure"
    fi
  done
  echo

  echo "## Auto Configurations"
  echo
  for module in "${modules[@]}"; do
    [[ "$(module_kind "$module")" == "autoconfigure" ]] || continue
    local dir
    dir="$(module_dir "$module")"
    local imports_file="$dir/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports"
    local factories_file="$dir/src/main/resources/META-INF/spring.factories"

    echo "### \`$module\`"
    echo
    echo "AutoConfiguration classes:"
    auto_configurations "$imports_file" || true
    echo
    echo "EnvironmentPostProcessor classes:"
    spring_factories_processors "$factories_file" || true
    echo
  done

  echo "## Configuration Properties"
  echo
  for module in "${modules[@]}"; do
    [[ "$(module_kind "$module")" == "autoconfigure" ]] || continue
    local dir
    dir="$(module_dir "$module")"
    local props
    props="$(configuration_properties "$dir")"
    [[ -n "$props" ]] || continue
    echo "### \`$module\`"
    echo
    printf '%s\n' "$props"
    echo
  done

  echo "## Dependencies"
  echo
  for module in "${modules[@]}"; do
    local dir
    dir="$(module_dir "$module")"
    local deps
    deps="$(dependency_lines "$dir/build.gradle.kts")"
    [[ -n "$deps" ]] || continue
    echo "### \`$module\`"
    echo
    printf '%s\n' "$deps" | while IFS= read -r dep; do
      printf -- '- `%s`\n' "$dep"
    done
    echo
  done

  echo "## Samples"
  echo
  for module in "${modules[@]}"; do
    [[ "$(module_kind "$module")" == "sample" ]] || continue
    printf -- '- `%s`\n' "$module"
  done
}

tmp_file="$(mktemp)"
generate > "$tmp_file"

if [[ "$CHECK" == "true" ]]; then
  if [[ ! -f "$OUTPUT_PATH" ]]; then
    echo "Missing generated facts file: $OUTPUT_PATH" >&2
    rm -f "$tmp_file"
    exit 1
  fi

  if ! diff -u "$OUTPUT_PATH" "$tmp_file"; then
    echo "Generated documentation facts are out of date." >&2
    rm -f "$tmp_file"
    exit 1
  fi

  rm -f "$tmp_file"
  exit 0
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"
mv "$tmp_file" "$OUTPUT_PATH"
echo "Wrote $OUTPUT_PATH"
